-- Documents the live Supabase schema. CREATE TABLE IF NOT EXISTS will not
-- change an existing pets table.

CREATE TABLE IF NOT EXISTS public.pet_types (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS public.pets (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  owner_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  pet_type_id integer NOT NULL REFERENCES public.pet_types(id),
  name varchar NOT NULL,
  breed varchar,
  sex varchar,
  age_months integer,
  color varchar,
  weight_kg real,
  about text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pets_owner_id_idx ON public.pets (owner_id);
